version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - consul
    networks:
      - mi-red

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - mi-red

  consul:
    image: consul:1.10.0
    hostname: consul
    ports:
      - "8500:8500"
    networks:
      - mi-red
  registrator:
    container_name: registrator
    image: gliderlabs/registrator:master
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: consul://consul:8500
    restart: always
    depends_on:
      - consul
networks:
  mi-red:
